### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by denismaster** [ViacheslavMezentsev/symbcs#1]
It would be great to add support for .NET Core.
You can also create a .NET Standard class library, this should add ability to integrate symbolic math to another open source projects.

**Comment by ViacheslavMezentsev** [comment]
Ok.

**Comment by ViacheslavMezentsev** [comment]
Solution changed. All platforms now supported (.net 2.0, .net core 2.0 and .net standard 2.0).
